const { app, BrowserWindow, Menu, shell, ipcMain, dialog, session } = require('electron');
const path = require('path');
const http = require('http');
const fs = require('fs');
const url = require('url');

const APP_DIR = __dirname;
const FIXED_PORT = 7777;
let mainWindow = null;
let server = null;
let SETTINGS_PATH = '';
function getSettingsPath() { if (!SETTINGS_PATH) SETTINGS_PATH = path.join(app.getPath('userData'), 'settings.json'); return SETTINGS_PATH; }
function loadSettings() { try { const fp = getSettingsPath(); if (fs.existsSync(fp)) return JSON.parse(fs.readFileSync(fp, 'utf8')); } catch (e) {} return {}; }
function saveSettings(obj) { try { fs.writeFileSync(getSettingsPath(), JSON.stringify(obj, null, 2)); } catch (e) {} }
function getLastFolder() { return loadSettings().lastFolder || null; }
function setLastFolder(p) { const s = loadSettings(); s.lastFolder = p; saveSettings(s); }
function clearLastFolder() { const s = loadSettings(); delete s.lastFolder; saveSettings(s); }
function getLastProjectId() { return loadSettings().lastProjectId || ''; }
function setLastProjectId(pid) { const s = loadSettings(); s.lastProjectId = pid || ''; saveSettings(s); }
const MIME = { '.html':'text/html; charset=utf-8','.htm':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.gif':'image/gif','.svg':'image/svg+xml','.ico':'image/x-icon','.woff':'font/woff','.woff2':'font/woff2','.ttf':'font/ttf','.wasm':'application/wasm','.data':'application/octet-stream','.tar':'application/x-tar','.gz':'application/gzip','.tflite':'application/octet-stream','.txt':'text/plain; charset=utf-8','.md':'text/markdown; charset=utf-8','.bin':'application/octet-stream' };
function getMime(fp) { return MIME[path.extname(fp).toLowerCase()] || 'application/octet-stream'; }
function focusWindow() { if (mainWindow && !mainWindow.isDestroyed()) { mainWindow.focus(); if (mainWindow.webContents) mainWindow.webContents.focus(); } }
function startServer() { return new Promise((resolve, reject) => { server = http.createServer((req, res) => { let pn; try { pn = decodeURIComponent(url.parse(req.url).pathname); } catch (e) { pn = '/'; } if (pn === '/' || pn === '') pn = '/index.html'; const resolved = path.resolve(path.join(APP_DIR, pn)); if (!resolved.startsWith(path.resolve(APP_DIR))) { res.writeHead(403); return res.end('Forbidden'); } fs.readFile(resolved, (err, data) => { if (err) { res.writeHead(404, {'Content-Type':'text/plain; charset=utf-8'}); return res.end('Not Found: ' + pn); } if (pn === '/index.html') { let html = data.toString('utf8'); if (html.indexOf('v12-fixes.js') === -1) html = html.replace('</body>', '<script src="/v12-fixes.js"></script>\n</body>'); data = Buffer.from(html, 'utf8'); } res.writeHead(200, {'Content-Type':getMime(resolved), 'Cache-Control':'no-cache'}); res.end(data); }); }); server.once('error', e => { if (e.code === 'EADDRINUSE') dialog.showErrorBox('خطا', 'پورت ' + FIXED_PORT + ' اشغال است.\nسایر نمونه‌های برنامه را ببندید.'); reject(e); }); server.listen(FIXED_PORT, '127.0.0.1', () => resolve(FIXED_PORT)); }); }
ipcMain.handle('fs:pickFolder', async () => { const r = await dialog.showOpenDialog(mainWindow, {title:'پوشه‌ای برای ذخیره انتخاب کنید',buttonLabel:'انتخاب این پوشه',properties:['openDirectory','createDirectory']}); focusWindow(); if (r.canceled || !r.filePaths || !r.filePaths[0]) return null; setLastFolder(r.filePaths[0]); return {path:r.filePaths[0],name:path.basename(r.filePaths[0]) || r.filePaths[0]}; });
ipcMain.handle('fs:getLastFolder', async () => { const p=getLastFolder(); if (!p) return null; try { if (!fs.existsSync(p) || !fs.statSync(p).isDirectory()) { clearLastFolder(); return null; } } catch(e) { return null; } return {path:p,name:path.basename(p)||p}; });
ipcMain.handle('fs:clearLastFolder', async () => { clearLastFolder(); return true; });
ipcMain.handle('fs:readFile', async (e, folder, name) => { const fp=path.join(folder,path.basename(name)); if(!fs.existsSync(fp)){const er=new Error('FileNotFound');er.name='NotFoundError';throw er;} return fs.readFileSync(fp,'utf8'); });
ipcMain.handle('fs:writeFile', async (e, folder, name, text) => { fs.writeFileSync(path.join(folder,path.basename(name)),text,'utf8'); return true; });
ipcMain.handle('fs:exists', async (e, folder, name) => { try{return fs.existsSync(path.join(folder,path.basename(name)));}catch(err){return false;} });
ipcMain.handle('app:setLastProjectId', async (e,pid) => {setLastProjectId(pid);return true;}); ipcMain.handle('app:getLastProjectId', async () => getLastProjectId()); ipcMain.handle('app:focus', async () => {focusWindow();return true;});
ipcMain.handle('debug:settings', async () => { const fp=getSettingsPath(); return {path:fp,exists:fs.existsSync(fp),content:fs.existsSync(fp)?fs.readFileSync(fp,'utf8'):null,userData:app.getPath('userData'),productName:app.getName()}; });
ipcMain.handle('fs:folderFromPath', async (e,p) => { if(!p)return null; try{if(!fs.existsSync(p)||!fs.statSync(p).isDirectory())return null;setLastFolder(p);return {path:p,name:path.basename(p)||p};}catch(err){return null;} });
ipcMain.on('alert-sync',(e,msg)=>{dialog.showMessageBoxSync(mainWindow,{type:'info',message:String(msg||''),buttons:['تأیید'],noLink:true,title:'دستیار پژوهش دینزی'});e.returnValue=true;});
ipcMain.on('confirm-sync',(e,msg)=>{const r=dialog.showMessageBoxSync(mainWindow,{type:'question',message:String(msg||''),buttons:['خیر','بله'],defaultId:1,cancelId:0,noLink:true,title:'دستیار پژوهش دینزی'});e.returnValue=r===1;});
async function createWindow(){let port;try{port=await startServer();}catch(e){app.quit();return;} mainWindow=new BrowserWindow({width:1400,height:900,minWidth:900,minHeight:600,show:false,backgroundColor:'#eef2f7',title:'دستیار پژوهش دینزی',icon:path.join(APP_DIR,'icon.ico'),webPreferences:{preload:path.join(APP_DIR,'preload.js'),contextIsolation:false,nodeIntegration:false,webSecurity:true,spellcheck:true,devTools:true}}); Menu.setApplicationMenu(null); mainWindow.webContents.session.setPermissionRequestHandler((wc,permission,cb)=>cb(permission==='media'||permission==='microphone'||permission==='audioCapture')); mainWindow.loadURL('http://127.0.0.1:'+port+'/'); mainWindow.once('ready-to-show',()=>{mainWindow.maximize();mainWindow.show();focusWindow();}); mainWindow.webContents.on('did-finish-load',focusWindow); mainWindow.on('focus',()=>{if(mainWindow.webContents)mainWindow.webContents.focus();}); mainWindow.webContents.on('before-input-event',(event,input)=>{if(input.key==='F12'||(input.control&&input.shift&&input.key.toLowerCase()==='i')){mainWindow.webContents.toggleDevTools();event.preventDefault();}}); mainWindow.webContents.setWindowOpenHandler(o=>{if(o.url.startsWith('http://127.0.0.1')||o.url.startsWith('http://localhost'))return {action:'allow'};shell.openExternal(o.url);return {action:'deny'};}); mainWindow.webContents.on('will-navigate',(e,u)=>{if(!u.startsWith('http://127.0.0.1')&&!u.startsWith('http://localhost')){e.preventDefault();shell.openExternal(u);}});}
const gotLock=app.requestSingleInstanceLock(); if(!gotLock)app.quit(); else {app.on('second-instance',()=>{if(mainWindow){if(mainWindow.isMinimized())mainWindow.restore();focusWindow();}});app.whenReady().then(createWindow);app.on('window-all-closed',()=>{if(server)server.close();if(process.platform!=='darwin')app.quit();});app.on('activate',()=>{if(BrowserWindow.getAllWindows().length===0)createWindow();});}
